[project]
name = "car"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hari", email = "anshari94432@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flake8>=7.3.0",
    "pytest>=9.1.1",
]

[project.scripts]
car = "car:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
